//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileOperator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.UsingService = new HashSet<UsingService>();
        }
    
        public string NumberPhone { get; set; }
        public int IdRate { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string PatronymicName { get; set; }
        public Nullable<System.DateTime> DateBirthday { get; set; }
        public string passportSerial { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DatePassport { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Rate Rate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsingService> UsingService { get; set; }
    }
}
